// Shared label maps used by server.js to render human-readable PDF output.
module.exports = {
  PERSONAL_FIELD_LABELS: {
    firstName: "First Name",
    middleName: "Middle Name",
    lastName: "Last Name",
    aliasFirstName: "Alias First Name",
    aliasLastName: "Alias Last Name",
    dateOfBirth: "Date of Birth",
    sinNumber: "SIN Number",
    mobileNo: "Mobile No",
    email: "Email",
    address: "Address",
    city: "City",
    province: "Province",
    postalCode: "Postal Code",
    maritalStatus: "Marital Status",
    maritalStatusChangeDate: "Marital Status Change Date",
    numberOfDependents: "Number of Dependents",
    spouseName: "Spouse Name",
    childTaxBenefit: "Receiving Child Tax Benefit",
    bankruptcyFirstName: "Bankruptcy First Name",
    bankruptcyMiddleName: "Bankruptcy Middle Name",
    bankruptcyLastName: "Bankruptcy Last Name",
    bankruptcyAliasFirstName: "Bankruptcy Alias First Name",
    bankruptcyAliasLastName: "Bankruptcy Alias Last Name",
    bankruptcyDateOfBirth: "Bankruptcy Date of Birth",
  },

  EMPLOYMENT_CATEGORY_LABELS: {
    employment: "Employment",
    unemployment: "Unemployment",
    retired: "Retired",
    disabled: "Disabled",
    selfEmployed: "Self-Employed",
  },

  EMPLOYMENT_FIELD_LABELS: {
    employerName: "Employer Name",
    jobTitle: "Job Title",
    dateOfJoining: "Date of Joining",
    lastDayOfWork: "Last Day of Work",
    retirementDate: "Retirement Date",
    pensionSource: "Pension Source",
    disabilityStartDate: "Disability Start Date",
    disabilityType: "Disability Type",
    businessName: "Business Name",
    businessType: "Business Type",
    operationsType: "Operations Type",
    businessAddress: "Business Address",
    businessStartDate: "Business Start Date",
    businessEndDate: "Business End Date",
    numberOfEmployees: "Number of Employees",
    ownershipPercentage: "Ownership Percentage",
    naicsCode: "NAICS Code",
  },

  ASSET_CATEGORY_LABELS: {
    properties: "Properties",
    vehicles: "Vehicles",
    policies: "Policies",
    securities: "Securities",
    otherAssets: "Other Assets",
  },

  ASSET_FIELD_LABELS: {
    propertyType: "Property Type",
    houseAddress: "Address",
    numberOnTitle: "Number of People on Title",
    propertyValue: "Property Value",
    houseMortgage: "Mortgage",
    residenceType: "Residence",
    houseMortgageProvider: "Mortgage Provider Name",
    mobileHomeName: "Name of Mobile Home",
    mobileHomeValue: "Value",
    mobileHomeMortgage: "Mortgage",
    mobileHomeMortgageProvider: "Mortgage Provider Name",
    mobileHomeSupportingDoc: "Supporting Doc for Value",
    trailerName: "Name of Trailer",
    trailerValue: "Value",
    trailerMortgage: "Mortgage",
    trailerMortgageProvider: "Mortgage Provider Name",
    trailerSupportingDoc: "Supporting Doc for Value",

    vehicleType: "Vehicle Type",
    vehicleYear: "Year",
    vehicleMake: "Make",
    vehicleModel: "Model",
    vehicleVIN: "VIN",
    vehicleMileage: "Mileage",
    vehicleCreditorName: "Creditor Name (if leased or loaned)",
    vehicleValue: "Vehicle Value",
    vehicleLoanValue: "Loan Value",

    policyType: "Policy Type",
    rrspProviderName: "Policy Provider Name",
    rrspTotalMarketValue: "Total Market Value",
    rrspLast12MonthContributions: "Last 12 Month Contributions",
    dpspProviderName: "Policy Provider Name",
    dpspTotalMarketValue: "Total Market Value",
    dpspLast12MonthContributions: "Last 12 Month Contributions",
    respProviderName: "Policy Provider Name",
    respTotalMarketValue: "Total Market Value",
    lifeInsuranceProviderName: "Policy Provider Name",
    lifeInsuranceValue: "Value",
    lifeInsuranceCashSurrenderValue: "Cash Surrender Value",
    otherPolicyName: "Policy Name",
    otherPolicyProviderName: "Policy Provider Name",
    otherPolicyTotalMarketValue: "Total Market Value",

    securityType: "Security Type",
    securityIssuerName: "Issuer Name",
    securityTotalMarketValue: "Total Market Value",

    otherAssetDescription: "Description",
    otherAssetValue: "Value",
    otherAssetLoanValue: "Loan Value",
    otherAssetCreditorName: "Creditor Name",
  },

  BANKRUPTCY_EQUITY_FIELD_LABELS: {
    bankruptcyEquityAssetDescription: "Asset Description",
    bankruptcyEquityAssetsValue: "Assets Value",
  },
};
